name: Pubblica su Aruba 🚀

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy su Aruba
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout codice
        uses: actions/checkout@v4
      
      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Build Sito
        run: |
          npm install
          npm run docs:build

      - name: 📂 Spedisci via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: docs/.vitepress/dist/
          server-dir: /
          
          # 👇 MODIFICA FONDAMENTALE: Mettiamo FALSE
          # Così smette di toccare le cartelle di backup e carica solo il sito
          dangerous-clean-slate: false
